In [1]:
import warnings
import numpy as np
import pandas as pd
import seaborn as sns
warnings.filterwarnings("ignore")
from matplotlib import pyplot as plt

In [2]:
df=pd.read_csv("exploratory_data.csv")
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130.0,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152.0,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,audi,gas,std,four,sedan,fwd,front,99.8,...,109.0,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,audi,gas,std,four,sedan,4wd,front,99.4,...,136.0,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

In [3]:
# checking for feature values distribution and their value counts
cat_col = df.dtypes[df.dtypes==object].index

for col in cat_col:
    print(df[col].value_counts())
    print("==================================")

toyota         32
nissan         18
mazda          15
mitsubishi     13
honda          13
volkswagen     12
subaru         12
peugeot        11
volvo          10
dodge           9
buick           8
bmw             8
plymouth        7
audi            6
saab            6
porsche         5
isuzu           4
jaguar          3
chevrolet       3
alfa-romero     3
renault         2
mercury         1
Name: CarName, dtype: int64
==================================
gas       182
diesel     19
Name: fueltype, dtype: int64
==================================
std      165
turbo     36
Name: aspiration, dtype: int64
==================================
four    113
two      88
Name: doornumber, dtype: int64
==================================
sedan          95
hatchback      68
wagon          24
hardtop         8
convertible     6
Name: carbody, dtype: int64
==================================
fwd    117
rwd     75
4wd      9
Name: drivewheel, dtype: int64
==================================
front    198
rear       3
Name: enginelocation, dtype: int64
==================================
ohc      144
ohcf      15
ohcv      13
dohc      12
l         12
rotor      4
dohcv      1
Name: enginetype, dtype: int64
==================================
four      157
six        23
five       10
eight       5
two         4
three       1
twelve      1
Name: cylindernumber, dtype: int64
==================================
mpfi    93
2bbl    64
idi     19
1bbl    11
spdi     9
4bbl     3
mfi      1
spfi     1
Name: fuelsystem, dtype: int64
==================================

In [4]:
df.drop(['CarName'], axis=1,inplace=True)

In [5]:
df.head()

,car_ID,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,...,enginesize,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price
0,1,3,gas,std,two,convertible,rwd,front,88.6,168.8,...,130.0,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0
1,2,3,gas,std,two,convertible,rwd,front,88.6,168.8,...,130.0,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0
2,3,1,gas,std,two,hatchback,rwd,front,94.5,171.2,...,152.0,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0
3,4,2,gas,std,four,sedan,fwd,front,99.8,176.6,...,109.0,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0
4,5,2,gas,std,four,sedan,4wd,front,99.4,176.6,...,136.0,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0

#### one hot encoding 

on features aspiration and doornumber

In [9]:
dummies = pd.get_dummies(df[['aspiration', 'doornumber']], drop_first=True)
df = pd.concat([df.drop(['aspiration', 'doornumber'],axis=1), dummies],axis=1)

In [10]:
df.head()

,car_ID,symboling,fueltype,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,...,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,aspiration_turbo,doornumber_two
0,1,3,gas,convertible,rwd,front,88.6,168.8,64.1,48.8,...,3.47,2.68,9.0,111,5000,21,27,13495.0,0,1
1,2,3,gas,convertible,rwd,front,88.6,168.8,64.1,48.8,...,3.47,2.68,9.0,111,5000,21,27,16500.0,0,1
2,3,1,gas,hatchback,rwd,front,94.5,171.2,65.5,52.4,...,2.68,3.47,9.0,154,5000,19,26,16500.0,0,1
3,4,2,gas,sedan,fwd,front,99.8,176.6,66.2,54.3,...,3.19,3.40,10.0,102,5500,24,30,13950.0,0,0
4,5,2,gas,sedan,4wd,front,99.4,176.6,66.4,54.3,...,3.19,3.40,8.0,115,5500,18,22,17450.0,0,0

In [11]:
# will removes rows which contains either hardtop or convertible or both as a carbody.
df = df[df["carbody"].str.contains("hardtop|convertible")  == False]

In [12]:
df.head(10)

,car_ID,symboling,fueltype,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,carheight,...,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,aspiration_turbo,doornumber_two
2,3,1,gas,hatchback,rwd,front,94.5,171.2,65.5,52.4,...,2.68,3.47,9.0,154,5000,19,26,16500.000,0,1
3,4,2,gas,sedan,fwd,front,99.8,176.6,66.2,54.3,...,3.19,3.40,10.0,102,5500,24,30,13950.000,0,0
4,5,2,gas,sedan,4wd,front,99.4,176.6,66.4,54.3,...,3.19,3.40,8.0,115,5500,18,22,17450.000,0,0
5,6,2,gas,sedan,fwd,front,99.8,177.3,66.3,53.1,...,3.19,3.40,8.5,110,5500,19,25,15250.000,0,1
6,7,1,gas,sedan,fwd,front,105.8,192.7,71.4,55.7,...,3.19,3.40,8.5,110,5500,19,25,17710.000,0,0
7,9,1,gas,sedan,fwd,front,105.8,192.7,71.4,55.9,...,3.13,3.40,8.3,140,5500,17,20,23875.000,1,0
8,10,0,gas,hatchback,4wd,front,99.5,178.2,67.9,52.0,...,3.13,3.40,7.0,160,5500,16,22,17859.167,1,1
9,11,2,gas,sedan,rwd,front,101.2,176.8,64.8,54.3,...,3.50,2.80,8.8,101,5800,23,29,16430.000,0,1
10,12,0,gas,sedan,rwd,front,101.2,176.8,64.8,54.3,...,3.50,2.80,8.8,101,5800,23,29,16925.000,0,0
11,13,0,gas,sedan,rwd,front,101.2,176.8,64.8,54.3,...,3.31,3.19,9.0,121,4250,21,28,20970.000,0,1

In [14]:
# will removes rows which contains 4wd as a drivewheel value
df = df[df["drivewheel"].str.contains("4wd")  == False]

In [15]:
df.drivewheel.head(10)

2     rwd
3     fwd
5     fwd
6     fwd
7     fwd
9     rwd
10    rwd
11    rwd
12    rwd
13    rwd
Name: drivewheel, dtype: object

In [16]:
df.drivewheel.tail(10)

191    rwd
192    rwd
193    rwd
194    rwd
195    rwd
196    rwd
197    rwd
198    rwd
199    rwd
200    rwd
Name: drivewheel, dtype: object

In [17]:
df.drop(['enginelocation'], axis=1,inplace=True)

In [18]:
df.head()

,car_ID,symboling,fueltype,carbody,drivewheel,wheelbase,carlength,carwidth,carheight,curbweight,...,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,aspiration_turbo,doornumber_two
2,3,1,gas,hatchback,rwd,94.5,171.2,65.5,52.4,2823,...,2.68,3.47,9.0,154,5000,19,26,16500.0,0,1
3,4,2,gas,sedan,fwd,99.8,176.6,66.2,54.3,2337,...,3.19,3.40,10.0,102,5500,24,30,13950.0,0,0
5,6,2,gas,sedan,fwd,99.8,177.3,66.3,53.1,2507,...,3.19,3.40,8.5,110,5500,19,25,15250.0,0,1
6,7,1,gas,sedan,fwd,105.8,192.7,71.4,55.7,2844,...,3.19,3.40,8.5,110,5500,19,25,17710.0,0,0
7,9,1,gas,sedan,fwd,105.8,192.7,71.4,55.9,3086,...,3.13,3.40,8.3,140,5500,17,20,23875.0,1,0